apiVersion: org.zitadel.crossplane.io/v1alpha1
kind: Member
metadata:
  annotations:
    meta.upbound.io/example-id: org/v1alpha1/member
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    orgId: ${data.zitadel_org.default.id}
    roles:
    - ORG_OWNER
    userId: ${data.zitadel_human_user.default.id}
