apiVersion: project.zitadel.crossplane.io/v1alpha1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: project/v1alpha1/role
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    displayName: display_name2
    group: role_group
    orgId: ${data.zitadel_org.default.id}
    projectId: ${data.zitadel_project.default.id}
    roleKey: super-user
