apiVersion: human.zitadel.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: human/v1alpha1/user
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    displayName: displayname
    email: test@zitadel.com
    firstName: firstname
    gender: GENDER_MALE
    initialPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    isEmailVerified: true
    isPhoneVerified: true
    lastName: lastname
    nickName: nickname
    orgId: ${data.zitadel_org.default.id}
    phone: "+41799999999"
    preferredLanguage: de
    userName: humanfull@localhost.com
